<script lang="ts">
	import { SMRT_VERSION_LABEL } from '$lib/version';
	import CodeBlock from '$lib/components/CodeBlock.svelte';
	import Callout from '$lib/components/Callout.svelte';

	// One class authored by you.
	const sourceClass = `// src/lib/models/product.ts
import { SmrtObject, smrt } from '@happyvertical/smrt-core';

@smrt({
  api: { include: ['list', 'get', 'create', 'update'] },
  cli: true,
  mcp: true
})
export class Product extends SmrtObject {
  collection = 'products';

  name: string = '';
  price: number = 0.0;
}`;

	// vite.config registration — the plugin runs the whole pipeline.
	const viteConfig = `// vite.config.ts
import { sveltekit } from '@sveltejs/kit/vite';
import { smrtPlugin } from '@happyvertical/smrt-core';

export default {
  plugins: [
    smrtPlugin(),   // scans, builds the manifest, generates routes
    sveltekit()
  ]
};`;

	// A representative generated collection route (list + create).
	const generatedCollectionRoute = `// src/routes/products/+server.ts
// Auto-generated by @smrt/core vite plugin
// DO NOT EDIT - changes will be overwritten

import { error, json } from '@sveltejs/kit';
import { getCollection } from '$lib/server/smrt';
import type { RequestHandler } from './$types';

// Fail-closed authorization (#1540): generated routes require an authenticated
// principal on \`locals\` unless explicitly marked \`@smrt({ api: { public } })\`.
const PUBLIC_ACCESS: boolean | 'read' = false;

function requireRouteAuth(locals: unknown, mutating: boolean): void {
  if (PUBLIC_ACCESS === true) return;
  if (PUBLIC_ACCESS === 'read' && !mutating) return;
  if (!hasAuthenticatedPrincipal(locals)) {
    throw error(401, 'Authentication required');
  }
}

export const GET: RequestHandler = async ({ locals, url }) => {
  requireRouteAuth(locals, false);
  const limit = Number(url.searchParams.get('limit')) || 50;
  const offset = Number(url.searchParams.get('offset')) || 0;

  const collection = await getCollection('Product');
  const items = await collection.list({ limit, offset });
  const count = await collection.count();

  const items_public = items.map((item) => item.toPublicJSON());
  return json({ items: items_public, count, limit, offset });
};

export const POST: RequestHandler = async ({ locals, request }) => {
  requireRouteAuth(locals, true);
  const data = applyWritablePolicy(await request.json());

  const collection = await getCollection('Product');
  const item = await collection.create(data);
  await item.save();
  return json(item.toPublicJSON(), { status: 201 });
};`;

	// The four generated surfaces, side by side.
	const fourSurfaces = `# REST  (src/routes/products/+server.ts, products/[id]/+server.ts)
GET  /products
POST /products
GET  /products/:id

# CLI   (virtual module smrt:cli)
smrt product:list
smrt product:create --name "Widget" --price 9.99

# MCP   (virtual module smrt:mcp)
product_list      # tool exposed to AI agents
product_create

# SQL   (virtual module smrt:schema)
CREATE TABLE products (
  id TEXT PRIMARY KEY,
  name TEXT,
  price DECIMAL,
  ...
);`;

	// Custom method → custom route.
	const customMethod = `@smrt({
  api: {
    include: ['get'],
    routes: {
      // item-scoped (instance method) → /products/[id]/restock
      restock: { method: 'POST' },
      // collection-scoped (static method) → /products/featured
      featured: { scope: 'collection', method: 'GET' }
    }
  }
})
export class Product extends SmrtObject {
  collection = 'products';
  stock: number = 0;

  // Instance method: routed under the [id] segment.
  async restock(amount: number) {
    this.stock += amount;
    await this.save();
    return { stock: this.stock };
  }

  // Static method: routed at the collection root.
  static async featured() {
    /* ... */
  }
}`;
</script>

<svelte:head>
	<title>How It Works | s-m-r-t</title>
	<meta
		name="description"
		content="Trace the SMRT codegen pipeline end to end: the Vite plugin scans your class, builds a manifest, and writes the generated REST, CLI, MCP, and SQL surfaces."
	/>
</svelte:head>

<article class="prose">
	<div class="page-head">
		<h1>How It Works</h1>
		<span class="version-badge">{SMRT_VERSION_LABEL}</span>
	</div>
	<p class="lead">
		You write one class. SMRT's Vite plugin scans it at build time, builds a manifest, and
		generates four call surfaces from that single definition: a REST API, a CLI, an MCP tool set,
		and the SQL schema. This page traces that pipeline end to end — what runs, what gets written,
		and where to find it.
	</p>

	<h2 id="pipeline">The pipeline</h2>
	<p>
		The whole thing is driven by <code>smrtPlugin()</code>, registered in your
		<code>vite.config.ts</code> alongside SvelteKit. There is no separate build step or codegen CLI
		to run — the plugin participates in Vite's own lifecycle, so generation happens on
		<code>dev</code> startup and on <code>build</code>.
	</p>

	<figure class="diagram">
		<svg viewBox="0 0 880 470" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="pipeline-title">
			<title id="pipeline-title"
				>Pipeline: your class is scanned by the OXC scanner into a manifest, which the SvelteKit
				generator turns into REST routes, CLI, MCP, and SQL schema.</title
			>
			<defs>
				<marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
					<path d="M 0 0 L 10 5 L 0 10 z" fill="var(--smrt-color-on-surface-variant, #888)" />
				</marker>
			</defs>

			<!-- Source -->
			<rect class="node node--source" x="20" y="30" width="190" height="70" rx="8" />
			<text class="node-label" x="115" y="60">Your class</text>
			<text class="node-sub" x="115" y="80">@smrt() + fields</text>

			<!-- arrow source -> scanner -->
			<line class="edge" x1="210" y1="65" x2="300" y2="65" marker-end="url(#arrow)" />

			<!-- Scanner -->
			<rect class="node node--step" x="300" y="30" width="200" height="70" rx="8" />
			<text class="node-label" x="400" y="58">OXC scanner</text>
			<text class="node-sub" x="400" y="78">smrt-scanner · AST</text>

			<!-- arrow scanner -> manifest -->
			<line class="edge" x1="500" y1="65" x2="590" y2="65" marker-end="url(#arrow)" />

			<!-- Manifest -->
			<rect class="node node--manifest" x="590" y="30" width="270" height="70" rx="8" />
			<text class="node-label" x="725" y="58">Manifest</text>
			<text class="node-sub" x="725" y="78">.smrt/manifest.json</text>

			<!-- arrow manifest -> generator (down) -->
			<line class="edge" x1="725" y1="100" x2="725" y2="150" marker-end="url(#arrow)" />

			<!-- Generator -->
			<rect class="node node--step" x="560" y="150" width="300" height="70" rx="8" />
			<text class="node-label" x="710" y="178">SvelteKit generator</text>
			<text class="node-sub" x="710" y="198">generateSvelteKitRoutes()</text>

			<!-- coherence check note -->
			<rect class="node node--check" x="20" y="150" width="490" height="70" rx="8" />
			<text class="node-label node-label--left" x="40" y="178">Build-time CLI ↔ API coherence check</text>
			<text class="node-sub node-sub--left" x="40" y="198">validateCliIncludeAgainstApi() — throws if a CLI command has no API route</text>

			<!-- arrow generator -> outputs (down, fan out) -->
			<line class="edge" x1="710" y1="220" x2="710" y2="280" marker-end="url(#arrow)" />
			<line class="edge edge--fan" x1="160" y1="300" x2="710" y2="300" />
			<line class="edge" x1="160" y1="300" x2="160" y2="340" marker-end="url(#arrow)" />
			<line class="edge" x1="345" y1="300" x2="345" y2="340" marker-end="url(#arrow)" />
			<line class="edge" x1="530" y1="300" x2="530" y2="340" marker-end="url(#arrow)" />
			<line class="edge" x1="715" y1="300" x2="715" y2="340" marker-end="url(#arrow)" />

			<!-- Four outputs -->
			<rect class="node node--out" x="70" y="340" width="180" height="90" rx="8" />
			<text class="node-label" x="160" y="370">REST</text>
			<text class="node-sub" x="160" y="392">+server.ts</text>
			<text class="node-sub" x="160" y="410">routes on disk</text>

			<rect class="node node--out" x="255" y="340" width="180" height="90" rx="8" />
			<text class="node-label" x="345" y="370">CLI</text>
			<text class="node-sub" x="345" y="392">smrt:cli</text>
			<text class="node-sub" x="345" y="410">virtual module</text>

			<rect class="node node--out" x="440" y="340" width="180" height="90" rx="8" />
			<text class="node-label" x="530" y="370">MCP</text>
			<text class="node-sub" x="530" y="392">smrt:mcp</text>
			<text class="node-sub" x="530" y="410">virtual module</text>

			<rect class="node node--out" x="625" y="340" width="180" height="90" rx="8" />
			<text class="node-label" x="715" y="370">SQL</text>
			<text class="node-sub" x="715" y="392">smrt:schema</text>
			<text class="node-sub" x="715" y="410">virtual module</text>
		</svg>
		<figcaption>
			One <code>@smrt()</code> class becomes four call surfaces. Only the REST routes are written to
			disk as files; the CLI, MCP, and SQL surfaces are served as Vite virtual modules built from
			the same manifest.
		</figcaption>
	</figure>

	<h2 id="step-1">1. You write the class</h2>
	<p>
		A SMRT object is a plain TypeScript class extending <code>SmrtObject</code>, annotated with
		<code>@smrt()</code>. The decorator config declares which surfaces to generate — here, four REST
		actions plus the CLI and MCP tool sets.
	</p>
	<CodeBlock code={sourceClass} filename="src/lib/models/product.ts" />

	<h2 id="step-2">2. The plugin scans it</h2>
	<p>
		Register <code>smrtPlugin()</code> in <code>vite.config.ts</code>. During
		<code>configResolved</code> (and <code>buildStart</code>), it calls its scanner over your source
		tree.
	</p>
	<CodeBlock code={viteConfig} filename="vite.config.ts" />
	<p>
		Scanning is handled by <code>@happyvertical/smrt-scanner</code>'s <code>OxcScanner</code>, a
		Rust-based <code>oxc-parser</code> AST pass. It walks your <code>.ts</code> files (it explicitly
		excludes <code>.svelte</code> files, since OXC chokes on <code>&lt;style&gt;</code> tags),
		reads each <code>@smrt()</code> class, and resolves inheritance. A scan error fails the build
		rather than silently emitting an empty manifest.
	</p>

	<h2 id="step-3">3. It builds the manifest</h2>
	<p>
		The scan produces a <em>manifest</em>: a description of every object — its fields, methods,
		decorator config, and collection name. The plugin writes it to
		<code>.smrt/manifest.json</code> so the CLI and other tools can discover your objects without
		re-scanning.
	</p>
	<Callout variant="note" title="The manifest is the single source">
		Every downstream surface is generated from the manifest, not from your source directly. That is
		why the REST API, CLI, MCP tools, and SQL schema can never drift apart — they are four
		projections of one description.
	</Callout>

	<h2 id="step-4">4. It generates the surfaces</h2>
	<p>
		With the manifest in hand, <code>generateSvelteKitRoutes()</code> writes the REST routes to
		disk, and the plugin registers virtual modules that materialize the other three surfaces on
		import.
	</p>

	<h3 id="generated-files">Where the generated REST files land</h3>
	<p>
		Routes are written under your routes directory, keyed by each object's
		<code>collection</code> name:
	</p>
	<table>
		<thead>
			<tr><th>Surface</th><th>Generated location</th><th>Handlers</th></tr>
		</thead>
		<tbody>
			<tr>
				<td>Collection</td>
				<td><code>src/routes/products/+server.ts</code></td>
				<td><code>GET</code> (list), <code>POST</code> (create)</td>
			</tr>
			<tr>
				<td>Item</td>
				<td><code>src/routes/products/[id]/+server.ts</code></td>
				<td><code>GET</code> (get), <code>PUT</code> (update), <code>DELETE</code> (delete)</td>
			</tr>
			<tr>
				<td>Custom (item)</td>
				<td><code>src/routes/products/[id]/restock/+server.ts</code></td>
				<td>your method, see below</td>
			</tr>
			<tr>
				<td>Custom (collection)</td>
				<td><code>src/routes/products/featured/+server.ts</code></td>
				<td>your static method, see below</td>
			</tr>
		</tbody>
	</table>
	<p>
		Every generated file begins with <code>{`// Auto-generated by @smrt/core vite plugin`}</code>
		and a <code>DO NOT EDIT</code> banner. On the next run the plugin deletes any
		<code>+server.ts</code> that starts with that header and regenerates it, so hand-edits are
		overwritten. The generated routes are added to <code>.gitignore</code>.
	</p>

	<h3 id="generated-route">What a generated route looks like</h3>
	<p>
		Here is the collection route for <code>Product</code>. Note the auth guard at the top of every
		handler, and that responses are serialized with <code>toPublicJSON()</code>, never raw
		<code>toJSON()</code>.
	</p>
	<CodeBlock code={generatedCollectionRoute} filename="src/routes/products/+server.ts" />

	<h3 id="route-auth">The fail-closed auth guard</h3>
	<p>
		Every generated CRUD and action handler calls <code>requireRouteAuth(locals, mutating)</code>
		before doing any work. It throws <code>401</code> unless the route is explicitly opted public,
		or <code>locals</code> carries a resolved, object-shaped principal
		(<code>locals.user</code>, <code>locals.session</code>, or the explicit
		<code>locals.smrtAuth === true</code> marker). Mutating verbs require auth even when reads are
		opted public. The full security model — what counts as a principal, how
		<code>@field</code> visibility works, and where your responsibilities begin — is on the
		<a href="/docs/security">Security</a> page.
	</p>
	<Callout variant="security" title="Generated routes are private by default">
		With no <code>api.public</code> set, the default is <code>false</code> and every route returns
		<code>401</code> until an authenticated principal is present. You opt in to public access
		deliberately, per object.
	</Callout>

	<h3 id="custom-methods">Custom-method routing</h3>
	<p>
		Any public method that is not one of the five CRUD actions (<code>list</code>,
		<code>get</code>, <code>create</code>, <code>update</code>, <code>delete</code>) becomes its
		own route. The <code>api.routes[name]</code> entry controls its HTTP method, URL path, and
		<strong>scope</strong>:
	</p>
	<ul>
		<li>
			<strong>Item scope</strong> (the default for instance methods) — routed under the
			<code>[id]</code> segment, e.g. <code>POST /products/[id]/restock</code>. The handler loads
			the instance with <code>collection.get(params.id)</code> before invoking your method.
		</li>
		<li>
			<strong>Collection scope</strong> — routed at the collection root, e.g.
			<code>GET /products/featured</code>. Collection-scoped routes require a
			<strong>static</strong> method; a non-static method declared with
			<code>scope: 'collection'</code> is skipped with a warning.
		</li>
	</ul>
	<CodeBlock code={customMethod} filename="src/lib/models/product.ts" />
	<p>
		The default URL segment is the method name (kebab-cased when the
		<code>kebabRoutes</code> option is on). An explicit
		<code>api.routes[name].path</code> always wins. Custom-action results are returned as
		<code>{`{ action, result }`}</code>, with the <code>result</code> recursively passed through
		<code>toPublicJSON()</code> so any returned objects still strip their sensitive fields.
	</p>

	<h2 id="four-surfaces">The four surfaces, side by side</h2>
	<p>From that one <code>Product</code> class you can now call into the same logic four ways:</p>
	<CodeBlock code={fourSurfaces} lang="text" />
	<p>
		The CLI, MCP, and SQL surfaces are exposed as Vite <em>virtual modules</em> —
		<code>smrt:cli</code>, <code>smrt:mcp</code>, and <code>smrt:schema</code> respectively —
		generated on import from the same manifest. (<code>smrt:routes</code>,
		<code>smrt:client</code>, <code>smrt:types</code>, and <code>smrt:manifest</code> are also
		available.) Only the REST routes are emitted as files on disk.
	</p>

	<h2 id="coherence">The CLI ↔ API coherence check</h2>
	<p>
		The generated CLI does not call your methods in-process — it invokes them <strong>over
		HTTP</strong>, through the generated API. So a CLI command for a method that has no API route
		would be dead on arrival. To catch that at build time,
		<code>validateCliIncludeAgainstApi()</code> runs during the build and <strong>throws</strong>
		if any class lists a command in <code>cli.include</code> that is not reachable via
		<code>api.include</code>.
	</p>
	<Callout variant="warning" title="Build fails on an unreachable CLI command">
		If you add <code>'archive'</code> to <code>cli.include</code> but never expose it through the
		API, the build stops with: <em>"…is declared in cli.include but is not exposed via the api."</em>
		Fix it by adding the method to <code>api.include</code>, or — if you really do invoke that CLI
		in-process with no HTTP — acknowledge it with
		<code>cli: {`{ skipApiCheck: true }`}</code>. The check is on by default and can be disabled
		globally with the plugin option <code>validateCliApiCoherence: false</code>.
	</Callout>

	<h2 id="trace">End to end</h2>
	<ol>
		<li>You author a <code>@smrt()</code> class with a <code>collection</code> name and fields.</li>
		<li>
			<code>smrtPlugin()</code> runs the <code>OxcScanner</code> over your <code>.ts</code> files on
			dev startup and build.
		</li>
		<li>The scan produces a manifest, written to <code>.smrt/manifest.json</code>.</li>
		<li>
			<code>generateSvelteKitRoutes()</code> writes <code>+server.ts</code> files under
			<code>src/routes/&lt;collection&gt;/</code>, each guarded by <code>requireRouteAuth</code>.
		</li>
		<li>
			The CLI, MCP, and SQL surfaces are served from <code>smrt:cli</code>,
			<code>smrt:mcp</code>, and <code>smrt:schema</code> virtual modules, all built from the same
			manifest.
		</li>
		<li>
			The build-time coherence check fails fast if a CLI command can't reach an API route.
		</li>
	</ol>
	<p>
		That is the entire codegen path. To go deeper on each object's fields, decorators, and
		lifecycle, see <a href="/docs/objects">Objects</a>; for the security defaults on the generated
		surface, see <a href="/docs/security">Security</a>.
	</p>

	<p class="source-note">
		Grounded in <code>packages/core/src/vite-plugin/sveltekit-generator.ts</code> and
		<code>packages/core/src/vite-plugin/index.ts</code> in the SMRT framework source.
	</p>
</article>

<style>
	.prose {
		max-width: 760px;
	}

	.page-head {
		display: flex;
		align-items: center;
		gap: 16px;
		flex-wrap: wrap;
	}

	.prose h1 {
		font-size: 2.5rem;
		font-weight: 600;
		margin-bottom: 0;
	}

	.version-badge {
		display: inline-block;
		font-family: var(--font-mono);
		font-size: 0.75rem;
		font-weight: 600;
		padding: 4px 10px;
		border-radius: var(--smrt-radius-sm, 4px);
		color: var(--smrt-color-primary, #e63946);
		background: color-mix(in srgb, var(--smrt-color-primary, #e63946) 12%, transparent);
		border: 1px solid color-mix(in srgb, var(--smrt-color-primary, #e63946) 35%, transparent);
	}

	.lead {
		font-size: 1.15rem;
		line-height: 1.6;
		color: var(--smrt-color-on-surface-variant, #555);
		margin: 16px 0 32px;
	}

	.prose h2 {
		font-size: 1.5rem;
		font-weight: 600;
		margin-top: 48px;
		margin-bottom: 12px;
		padding-top: 12px;
		border-top: 1px solid var(--smrt-color-outline-variant, #eee);
	}

	.prose h3 {
		font-size: 1.15rem;
		font-weight: 600;
		margin-top: 32px;
		margin-bottom: 10px;
	}

	.prose p,
	.prose li {
		line-height: 1.7;
		color: var(--smrt-color-on-surface, #1a1a1a);
	}

	.prose ul,
	.prose ol {
		padding-left: 24px;
	}

	.prose li {
		margin-bottom: 10px;
	}

	.prose a {
		color: var(--smrt-color-primary, #e63946);
		text-decoration: none;
	}

	.prose a:hover {
		text-decoration: underline;
	}

	.prose :not(pre) > code {
		font-family: var(--font-mono);
		font-size: 0.85em;
		padding: 1px 6px;
		border-radius: 3px;
		background: var(--smrt-color-surface-container, #f0f0f0);
		color: var(--smrt-color-on-surface, #1a1a1a);
	}

	.prose table {
		width: 100%;
		border-collapse: collapse;
		margin: 16px 0 24px;
		font-size: 0.9rem;
	}

	.prose th,
	.prose td {
		text-align: left;
		padding: 8px 12px;
		border-bottom: 1px solid var(--smrt-color-outline-variant, #eee);
		vertical-align: top;
	}

	.prose th {
		font-weight: 600;
		color: var(--smrt-color-on-surface-variant, #555);
		border-bottom: 2px solid var(--smrt-color-outline, #ddd);
	}

	.diagram {
		margin: 24px 0 32px;
		padding: 20px;
		border: 1px solid var(--smrt-color-outline-variant, #e5e5e5);
		border-radius: var(--smrt-radius-md, 8px);
		background: var(--smrt-color-surface-container-low, #fafafa);
	}

	.diagram svg {
		width: 100%;
		height: auto;
	}

	.diagram figcaption {
		margin-top: 12px;
		font-size: 0.85rem;
		line-height: 1.5;
		color: var(--smrt-color-on-surface-variant, #666);
	}

	/* Diagram nodes */
	.node {
		fill: var(--smrt-color-surface-container, #fff);
		stroke: var(--smrt-color-outline, #ccc);
		stroke-width: 1.5;
	}

	.node--source {
		fill: color-mix(in srgb, var(--smrt-color-primary, #e63946) 12%, var(--smrt-color-surface, #fff));
		stroke: var(--smrt-color-primary, #e63946);
	}

	.node--manifest {
		fill: color-mix(in srgb, var(--smrt-color-success, #059669) 12%, var(--smrt-color-surface, #fff));
		stroke: var(--smrt-color-success, #059669);
	}

	.node--out {
		fill: var(--smrt-color-surface-container-high, #f2f2f2);
		stroke: var(--smrt-color-outline, #bbb);
	}

	.node--check {
		fill: color-mix(in srgb, var(--smrt-color-warning, #d97706) 10%, var(--smrt-color-surface, #fff));
		stroke: var(--smrt-color-warning, #d97706);
		stroke-dasharray: 5 4;
	}

	.node-label {
		fill: var(--smrt-color-on-surface, #1a1a1a);
		font-family: var(--font-sans);
		font-size: 16px;
		font-weight: 600;
		text-anchor: middle;
	}

	.node-label--left {
		text-anchor: start;
	}

	.node-sub {
		fill: var(--smrt-color-on-surface-variant, #666);
		font-family: var(--font-mono);
		font-size: 12px;
		text-anchor: middle;
	}

	.node-sub--left {
		text-anchor: start;
	}

	.edge {
		stroke: var(--smrt-color-on-surface-variant, #888);
		stroke-width: 2;
		fill: none;
	}

	.edge--fan {
		stroke-dasharray: 0;
	}

	.source-note {
		margin-top: 48px;
		padding-top: 16px;
		border-top: 1px solid var(--smrt-color-outline-variant, #eee);
		font-size: 0.85rem;
		color: var(--smrt-color-on-surface-variant, #888);
	}

	@media (max-width: 600px) {
		.prose h1 {
			font-size: 2rem;
		}
	}
</style>
